package WebRHINO::Model::Rhino;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'WebRHINO::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:rhino:rhino_data',
        user => 'pinky',
        password => 'OngoBongoMaktub-999',
    }
);

=head1 NAME

WebRHINO::Model::Rhino - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<WebRHINO>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<WebRHINO::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
